apiVersion: apps/v1
kind: {{ if eq .Values.proxy.kind "daemonset" }}DaemonSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ include "quic-proxy-waf.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quic-proxy-waf.proxy.labels" . | nindent 4 }}
spec:
{{- if eq .Values.proxy.kind "deployment" }}
  replicas: {{ .Values.proxy.replicaCount }}
{{- else if eq .Values.proxy.kind "daemonset" }}
  updateStrategy:
    {{- toYaml .Values.daemonset.updateStrategy | nindent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "quic-proxy-waf.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quic-proxy-waf.proxy.labels" . | nindent 8 }}
    spec:
{{- if and (eq .Values.proxy.kind "daemonset") .Values.proxy.ports.useHostPorts }}
      hostNetwork: {{ .Values.daemonset.hostNetwork }}
      dnsPolicy: {{ .Values.daemonset.dnsPolicy }}
{{- end }}
      containers:
      - name: proxy
        image: {{ include "quic-proxy-waf.proxy.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.proxy.ports.http }}
{{- if and (eq .Values.proxy.kind "daemonset") .Values.proxy.ports.useHostPorts }}
          hostPort: {{ .Values.proxy.ports.http }}
{{- end }}
          protocol: TCP
          name: http
        - containerPort: {{ .Values.proxy.ports.https }}
{{- if and (eq .Values.proxy.kind "daemonset") .Values.proxy.ports.useHostPorts }}
          hostPort: {{ .Values.proxy.ports.https }}
{{- end }}
          protocol: TCP
          name: https
{{- if and (eq .Values.proxy.kind "daemonset") .Values.proxy.ports.useHostPorts }}
        - containerPort: {{ .Values.proxy.ports.https }}
          hostPort: {{ .Values.proxy.ports.https }}
          protocol: UDP
          name: http3
{{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "quic-proxy-waf.fullname" . }}-config
        resources:
          {{- toYaml .Values.proxy.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /_gwhealthz
            port: {{ .Values.proxy.ports.http }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_gwhealthz
            port: {{ .Values.proxy.ports.http }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: tls-private
          mountPath: /etc/ssl/private
          readOnly: true
        securityContext:
          # Running as root is required for binding to ports 80/443
          runAsUser: 0
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ .Values.proxy.tls.secretName }}
          items:
          - key: tls.crt
            path: tls.crt
      - name: tls-private
        secret:
          secretName: {{ .Values.proxy.tls.secretName }}
          items:
          - key: tls.key
            path: tls.key
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}