{{- if .Values.waf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quic-proxy-waf.fullname" . }}-waf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quic-proxy-waf.waf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.waf.replicaCount }}
  selector:
    matchLabels:
      {{- include "quic-proxy-waf.waf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quic-proxy-waf.waf.labels" . | nindent 8 }}
    spec:
      containers:
      - name: waf
        image: {{ include "quic-proxy-waf.waf.image" . }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.waf.service.port }}
          protocol: TCP
          name: http
        env:
        - name: WAF_PORT
          value: {{ .Values.waf.service.port | quote }}
        - name: GIN_MODE
          value: "release"
        resources:
          {{- toYaml .Values.waf.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.waf.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.waf.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}