apiVersion: v2
name: quic-proxy-waf
description: A high-performance reverse proxy with integrated Coraza WAF and OWASP Core Rule Set
version: 1.2.0
appVersion: "1.2.0"
type: application
keywords:
  - proxy
  - reverse-proxy
  - waf
  - security
  - coraza
  - owasp
home: https://github.com/pmh-only/quic-proxy
maintainers:
  - name: pmh-only
    email: pmh@pmh.codes
sources:
  - https://github.com/pmh-only/quic-proxy