# Example values for DaemonSet deployment with host ports
# This configuration deploys the proxy as a DaemonSet with host network access

global:
  registry: ghcr.io/pmh-only/quic-proxy
  tag: "1.2.0"
  imagePullPolicy: IfNotPresent

# WAF service configuration (unchanged)
waf:
  enabled: true
  replicaCount: 2
  image:
    repository: coraza-waf
    tag: ""
  service:
    port: 9000
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

# Proxy service configuration for DaemonSet
proxy:
  # Use DaemonSet instead of Deployment
  kind: daemonset
  # replicaCount is ignored for DaemonSets (runs on all nodes)
  replicaCount: 3
  image:
    repository: quic-proxy
    tag: ""
  
  # Backend configuration
  backend:
    host: "your-backend-service"
    port: 8080
  
  # Server ports with host port binding
  ports:
    http: 80
    https: 443
    # Enable host ports for direct node access
    useHostPorts: true
  
  # WAF integration
  waf:
    enabled: true
    timeout: 1000
  
  # TLS configuration
  tls:
    certFile: "/etc/ssl/certs/tls.crt"
    keyFile: "/etc/ssl/private/tls.key"
    secretName: "tls-certificate"
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "1000m"

# Service configuration (disabled when using host ports)
service:
  type: LoadBalancer
  annotations: {}

# Network policies
networkPolicy:
  enabled: true

# Pod disruption budgets (disabled for DaemonSets)
podDisruptionBudget:
  enabled: false
  proxy:
    minAvailable: 2
  waf:
    minAvailable: 1

# Security context
securityContext:
  runAsNonRoot: false  # Proxy needs root for port 80/443
  runAsUser: 0

# Node selector, tolerations and affinity
nodeSelector: {}
# Example: Only run on edge nodes
# nodeSelector:
#   node-role.kubernetes.io/edge: "true"

tolerations: []
# Example: Tolerate edge node taints
# tolerations:
# - key: "edge"
#   operator: "Equal"
#   value: "true"
#   effect: "NoSchedule"

affinity: {}

# DaemonSet specific settings
daemonset:
  # Update strategy for DaemonSets
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  # Use host network for direct port access
  hostNetwork: true
  # Use host DNS when using host network
  dnsPolicy: ClusterFirstWithHostNet

# Additional labels
labels: {}

# Additional annotations
annotations: {}